export const EQUIPMENT_CATEGORIES = [
  { id: 'vessels', title: '1. Ёмкости и аппараты (ГОСТ 2.793-79)' },
  { id: 'hydraulics', title: '2. Гидравлика и приводы (ГОСТ 2.782-96)' },
  { id: 'valves', title: '3. Трубопроводная арматура (ГОСТ 2.784-96)' },
  { id: 'thermal', title: '4. Теплообменное оборудование' },
  { id: 'sensors', title: '5. Приборы КИПиА (ГОСТ 21.404-93)' },
  { id: 'mechanics', title: '6. Механический транспорт' },
];

export const EQUIPMENT_TYPES = {
  // 1. Ёмкости и аппараты
  tank_vertical: {
    type: 'tank_vertical',
    category: 'vessels',
    title: 'Вертикальный резервуар',
    standard: 'ГОСТ 2.793-79',
    width: 100,
    height: 120,
    defaultTag: 'Tank_Level_01',
    defaultUnit: '%',
    defaultMin: 0,
    defaultMax: 100,
    hasSetpoint: false,
  },
  tank_horizontal: {
    type: 'tank_horizontal',
    category: 'vessels',
    title: 'Горизонтальная цистерна',
    standard: 'ГОСТ 2.793-79',
    width: 140,
    height: 80,
    defaultTag: 'Cistern_Level_01',
    defaultUnit: 'м³',
    defaultMin: 0,
    defaultMax: 50,
    hasSetpoint: false,
  },
  boiler: {
    type: 'boiler',
    category: 'vessels',
    title: 'Котёл нагревательный',
    standard: 'ГОСТ 2.793-79',
    width: 120,
    height: 120,
    defaultTag: 'Boiler_Temp_01',
    defaultSetpoint: 'Temp_Setpoint_01',
    defaultUnit: '°C',
    defaultMin: 20,
    defaultMax: 110,
    hasSetpoint: true,
  },

  // 2. Гидравлика и приводы
  pump: {
    type: 'pump',
    category: 'hydraulics',
    title: 'Центробежный насос',
    standard: 'ГОСТ 2.782-96',
    width: 80,
    height: 80,
    defaultTag: 'Pump_01_Status',
    defaultUnit: '',
    defaultMin: 0,
    defaultMax: 1,
    hasSetpoint: false,
  },
  fan: {
    type: 'fan',
    category: 'hydraulics',
    title: 'Вентилятор / Компрессор',
    standard: 'ГОСТ 2.780-96',
    width: 80,
    height: 80,
    defaultTag: 'Fan_01_Speed',
    defaultUnit: 'об/мин',
    defaultMin: 0,
    defaultMax: 3000,
    hasSetpoint: true,
  },
  motor: {
    type: 'motor',
    category: 'hydraulics',
    title: 'Электромотор (M)',
    standard: 'ГОСТ 2.780-96',
    width: 80,
    height: 80,
    defaultTag: 'Motor_01_Current',
    defaultUnit: 'А',
    defaultMin: 0,
    defaultMax: 50,
    hasSetpoint: false,
  },

  // 3. Трубопроводная арматура
  valve: {
    type: 'valve',
    category: 'valves',
    title: 'Запорный клапан (⧓)',
    standard: 'ГОСТ 2.784-96',
    width: 80,
    height: 60,
    defaultTag: 'Valve_01_State',
    defaultUnit: '',
    defaultMin: 0,
    defaultMax: 1,
    hasSetpoint: false,
  },
  control_valve: {
    type: 'control_valve',
    category: 'valves',
    title: 'Регулирующий клапан',
    standard: 'ГОСТ 2.784-96',
    width: 80,
    height: 80,
    defaultTag: 'Ctrl_Valve_Position',
    defaultSetpoint: 'Ctrl_Valve_Setpoint',
    defaultUnit: '%',
    defaultMin: 0,
    defaultMax: 100,
    hasSetpoint: true,
  },
  gate_valve: {
    type: 'gate_valve',
    category: 'valves',
    title: 'Задвижка клиновая',
    standard: 'ГОСТ 2.785-70',
    width: 80,
    height: 80,
    defaultTag: 'Gate_Valve_01',
    defaultUnit: '',
    defaultMin: 0,
    defaultMax: 1,
    hasSetpoint: false,
  },

  // 4. Теплообменное оборудование
  heat_exchanger: {
    type: 'heat_exchanger',
    category: 'thermal',
    title: 'Теплообменник',
    standard: 'ГОСТ 2.793-79',
    width: 100,
    height: 80,
    defaultTag: 'HeatEx_Temp_Out',
    defaultUnit: '°C',
    defaultMin: 10,
    defaultMax: 95,
    hasSetpoint: false,
  },
  heater: {
    type: 'heater',
    category: 'thermal',
    title: 'Электрический ТЭН',
    standard: 'ГОСТ 2.793-79',
    width: 80,
    height: 80,
    defaultTag: 'Heater_01_Power',
    defaultUnit: 'кВт',
    defaultMin: 0,
    defaultMax: 15,
    hasSetpoint: true,
  },

  // 5. Приборы КИПиА
  sensor_temp: {
    type: 'sensor_temp',
    category: 'sensors',
    title: 'Датчик температуры (T)',
    standard: 'ГОСТ 21.404-93',
    symbol: 'T',
    width: 80,
    height: 80,
    defaultTag: 'Boiler_Temp_01',
    defaultUnit: '°C',
    defaultMin: 0,
    defaultMax: 120,
    hasSetpoint: false,
  },
  sensor_pressure: {
    type: 'sensor_pressure',
    category: 'sensors',
    title: 'Датчик давления (P)',
    standard: 'ГОСТ 21.404-93',
    symbol: 'P',
    width: 80,
    height: 80,
    defaultTag: 'System_Pressure_01',
    defaultUnit: 'бар',
    defaultMin: 0,
    defaultMax: 10,
    hasSetpoint: false,
  },
  sensor_level: {
    type: 'sensor_level',
    category: 'sensors',
    title: 'Датчик уровня (L)',
    standard: 'ГОСТ 21.404-93',
    symbol: 'L',
    width: 80,
    height: 80,
    defaultTag: 'Tank_Level_01',
    defaultUnit: '%',
    defaultMin: 0,
    defaultMax: 100,
    hasSetpoint: false,
  },
  sensor_flow: {
    type: 'sensor_flow',
    category: 'sensors',
    title: 'Расходомер (F)',
    standard: 'ГОСТ 21.404-93',
    symbol: 'F',
    width: 80,
    height: 80,
    defaultTag: 'Water_Flow_01',
    defaultUnit: 'м³/ч',
    defaultMin: 0,
    defaultMax: 25,
    hasSetpoint: false,
  },

  // 6. Механика
  conveyor: {
    type: 'conveyor',
    category: 'mechanics',
    title: 'Конвейер / Транспортер',
    standard: 'ГОСТ 2.780',
    width: 140,
    height: 60,
    defaultTag: 'Conveyor_01_Run',
    defaultUnit: 'м/с',
    defaultMin: 0,
    defaultMax: 2,
    hasSetpoint: false,
  },
};

export const COMMON_SCADA_TAGS = [
  'Boiler_Temp_01',
  'System_Pressure_01',
  'Pump_01_Status',
  'Alarm_Code_01',
  'Temp_Setpoint_01',
  'Tank_Level_01',
  'Water_Flow_01',
  'Fan_01_Speed',
  'Heater_01_Power',
];

export const INITIAL_DEMO_SCHEMA = {
  version: '1.0',
  title: 'Технологическая схема котельного контура',
  grid: {
    width: 1200,
    height: 700,
    cell_size: 20,
  },
  widgets: [
    {
      id: 'boiler_01',
      type: 'boiler',
      title: 'Котёл отопления №1',
      x: 100,
      y: 160,
      tag_id: 'Boiler_Temp_01',
      tag_setpoint: 'Temp_Setpoint_01',
      unit: '°C',
      min_val: 20.0,
      max_val: 100.0,
    },
    {
      id: 'temp_sensor_01',
      type: 'sensor_temp',
      title: 'Температура подачи',
      x: 260,
      y: 120,
      tag_id: 'Boiler_Temp_01',
      tag_setpoint: null,
      unit: '°C',
      min_val: 0.0,
      max_val: 120.0,
    },
    {
      id: 'pump_01',
      type: 'pump',
      title: 'Сетевой насос №1',
      x: 420,
      y: 180,
      tag_id: 'Pump_01_Status',
      tag_setpoint: null,
      unit: '',
      min_val: 0,
      max_val: 1,
    },
    {
      id: 'press_sensor_01',
      type: 'sensor_pressure',
      title: 'Давление в контуре',
      x: 580,
      y: 120,
      tag_id: 'System_Pressure_01',
      tag_setpoint: null,
      unit: 'бар',
      min_val: 0.0,
      max_val: 6.0,
    },
    {
      id: 'valve_01',
      type: 'valve',
      title: 'Отсечной клапан',
      x: 740,
      y: 190,
      tag_id: 'Valve_01_State',
      tag_setpoint: null,
      unit: '',
      min_val: 0,
      max_val: 1,
    },
    {
      id: 'tank_01',
      type: 'tank_vertical',
      title: 'Расширительный бак',
      x: 900,
      y: 140,
      tag_id: 'Tank_Level_01',
      tag_setpoint: null,
      unit: '%',
      min_val: 0,
      max_val: 100,
    },
  ],
};
